DROP TABLE  MMAPST.ST_CUST_CARD;
CREATE TABLE MMAPST.ST_CUST_CARD
(
 ETL_DATE NUMBER(8)
,TX_DATE DATE
,PERIOD_ID NUMBER(8)
,CARD_ID VARCHAR2(50)
,ACCOUNT_ID VARCHAR2(50)
,OPEN_BRANCH VARCHAR2(50)
,ISSU_DT DATE
,CARDSTS_ID VARCHAR2(50)
,CREATECARD_DT DATE
,FEE_YAMT NUMBER(20,8)
,CUSTOMER_ID VARCHAR2(50)
,CRDTYP_ID VARCHAR2(50)
,EFFE_DT DATE
,CLOS_DT DATE
,EXPR_DT DATE
,B_TXLM NUMBER(20,8)
,AUTH_ID VARCHAR2(50)
,BCARDNO VARCHAR2(50)
,LM_BAIl NUMBER(20,8)
,CARD_FG VARCHAR2(50)
,ICCARD_ID VARCHAR2(50)
,SVC_NAME VARCHAR2(50)
);

INSERT INTO MMAPST.ST_CUST_CARD
(
ETL_DATE
,TX_DATE
,PERIOD_ID
,CARD_ID
,ACCOUNT_ID
,OPEN_BRANCH
,ISSU_DT
,CARDSTS_ID
,CREATECARD_DT
,FEE_YAMT
,CUSTOMER_ID
,CRDTYP_ID
,EFFE_DT
,CLOS_DT
,EXPR_DT
,B_TXLM
,AUTH_ID
,BCARDNO
,LM_BAIl
,CARD_FG
,ICCARD_ID
,SVC_NAME
)
SELECT 
TO_NUMBER(to_char(SYSDATE,'YYYYMMDD')) AS ETL_DATE
,a.TX_DT AS TX_DATE
,TO_NUMBER(to_char(SYSDATE,'YYYYMMDD')) AS PERIOD_ID
,TRIM(CARD_ORG)
,TRIM(ACC_ORG)
,TRIM(BRNH_ID)
,TRIM(ISSU_DT)
,TRIM(CARDSTS_ID)
,TRIM(CREATECARD_DT)
,TRIM(FEE_YAMT)
,TRIM(a.CIF_ORG)
,NVL(TRIM(CRDTYP_ID),'-')
,TRIM(EFFE_DT)
,TRIM(CLOS_DT)
,TRIM(EXPR_DT)
,TRIM(B_TXLM)
,TRIM(AUTH_ID)
,TRIM(BCARDNO)
,TRIM(LM_BAIl)
,TRIM(CARD_FG)
,TRIM(ICCARD_ID)
,TRIM(SVC_NAME)
FROM DMMKT_ACDRCARD a
INNER JOIN MMAPST.DMMKT_CSMAST b
ON a.CIF_ORG=b.CIF_ORG
WHERE TRIM(b.CIFTYP_ID)='I'

