TRUNCATE TABLE  MMAPST.ST_CUST_CARD;
INSERT INTO MMAPST.ST_CUST_CARD
(
ETL_DATE
,TX_DATE
,PERIOD_ID
,CARD_ORG
,ACC_ORG
,BRNH_ID
,ISSU_DT
,CARDSTS_ID
,CREATECARD_DT
,FEE_YAMT
,CUSTOMER_ID
,CRDTYP_ID
,EFFE_DT
,CLOS_DT
,EXPR_DT
,B_TXLM
,AUTH_ID
,BCARDNO
,LM_BAIl
,CARD_FG
,ICCARD_ID
,SVC_NAME
)
SELECT 
TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDD')) AS ETL_DATE
,A.TX_DT AS TX_DATE
,TO_NUMBER(TO_CHAR(A.TX_DT,'YYYYMMDD')) AS PERIOD_ID
,TRIM(CARD_ORG)
,TRIM(ACC_ORG)
,TRIM(BRNH_ID)
,ISSU_DT
,TRIM(CARDSTS_ID)
,CREATECARD_DT
,TRIM(FEE_YAMT)
,TRIM(A.CIF_ORG)
,TRIM(CRDTYP_ID)
,EFFE_DT
,CLOS_DT
,EXPR_DT
,TRIM(B_TXLM)
,TRIM(AUTH_ID)
,TRIM(BCARDNO)
,TRIM(LM_BAIL)
,TRIM(CARD_FG)
,TRIM(ICCARD_ID)
,TRIM(SVC_NAME)
FROM MMAPST.DMMKT_ACDRCARD A
INNER JOIN MMAPST.DMMKT_CSMAST B
ON A.CIF_ORG=B.CIF_ORG	--个人客户
AND TRIM(B.CIFTYP_ID)='I'
INNER JOIN MMAPST.DMMKT_SYSTEM_DATE C	--"当日"数据
ON A.TX_DT=TO_DATE(C.TX_DATE,'YYYYMMDD');
