DELETE FROM MMAPST.ST_CUSTOMER;

INSERT INTO MMAPST.ST_CUSTOMER 
(
ETL_DATE
,TX_DATE
,PERIOD_ID
,CUSTOMER_ID
,CUST_NAME
,AGE
,BIRTH_DT
,GENDER_CODE
,EDU_CODE
,MARITALSTS_CODE
,CMP_DEP
,OCUP_CODE
,OCCP_CODE
,POSITION_CODE
,POSITION_TITLE_CODE
,INCOME
,INCOME_RANGE
,RESD_CODE
,COUNTRY_CODE
,RACE_CODE
,IDTYPE_CODE
,IDCODE
,IDCOUNTRY_CODE
,IDEXP_DT
,IDISS_DT
,CUST_BRANCH
,OPEN_BRANCH
,OWN_BRANCH
,FIN_MANAGER
,FIN_MANAGER_PHONE
,CIFOPEN_DT
,CIFCLOSE_DT
,CIF_LVL_CODE
,RISK_LVL_CODE
,RATING_LVL_CODE
,LOAN_AMT
,CONTRIBUTION_RATE
,EMP_IND
,BLACKLIST_IND
,WHITELIST_IND
,BREAK_IND
,CUST_STATUS_IND
) 
SELECT 
 TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDD')) AS ETL_DATE 
 ,TX_DT   
 ,TO_NUMBER(TO_CHAR(TX_DT,'YYYYMMDD')) AS PERIOD_ID 
 ,TRIM(CIF_ORG) AS CIF_ORG
 ,TRIM(CIF_NM) AS CIF_NM
 ,FLOOR(MONTHS_BETWEEN(SYSDATE,BIRTH_DT)/12) AS AGE     
 ,BIRTH_DT 
 ,NVL(TRIM(GENDER_ID),'-') AS GENDER_ID
 ,NVL(TRIM(EDU_ID),'-')  AS EDU_ID
 ,NVL(TRIM(MARITALSTS_ID),'-')  AS MARITALSTS_ID
 ,TRIM(CIFCOMP_NM)  AS CIFCOMP_NM
 ,NVL(TRIM(INDTYP_ID),'-')  AS OCUP_ID
 ,NVL(TRIM(OCCP_ID),'-')  AS OCCP_ID
 ,NVL(TRIM(JOBDES_ID),'-')  AS JOBDES_ID
 ,NVL(TRIM(PROFTITL_ID),'-')  AS PROFTITL_ID
 ,NULL AS INCOME  
 ,NULL AS INCOME_RANGE 
 ,NVL(TRIM(RESICNTRY_ID),'-')  AS RESICNTRY_ID
 ,NVL(TRIM(CITIZEN_ID),'-')  AS CITIZEN_ID
 ,NVL(TRIM(RACETYP_ID),'-')  AS RACETYP_ID
 ,NULL AS IDTYPE_CODE  
 ,NULL AS IDCODE
 ,NULL AS IDCOUNTRY_CODE  
 ,NULL AS IDEXP_DT 
 ,NULL AS IDISS_DT   
 ,TRIM(MGRBRANCH_ID)  AS MGRBRANCH_ID
 ,TRIM(OPBRANCH_ID)  AS OPBRANCH_ID
 ,COALESCE(CASE when TRIM(MGRBRANCH_ID)='-' THEN NULL ELSE TRIM(MGRBRANCH_ID) END,OPBRANCH_ID) AS OWNBRANCH_CODE
 ,NULL AS FIN_MANAGER
 ,NULL AS FIN_MANAGER_PHONE
 ,CIFOPEN_DT
 ,CIFCLOSE_DT
 ,NVL(TRIM(CIF_LVL),'-') AS CIF_LVL
 ,NVL(TRIM(RISK_LVL),'-') AS RISK_LVL
 ,NULL AS RATING_LVL_CODE 
 ,NULL AS LOAN_AMT
 ,NULL AS CONTRIBUTION_RATE
 ,(CASE WHEN staff_FG='Y' THEN 1 ELSE 0 END) AS EMP_IND
 ,NULL AS BLACKLIST_IND
 ,NULL AS WHITELIST_IND
 ,NULL AS BREAK_IND
 ,NULL ASCUST_STATUS_IND                                                                              
FROM 
MMAPST.DMMKT_CSMAST 
WHERE TRIM(CIFTYP_ID)='I'
;
COMMIT;

