/*
目标表：产品信息表(ST_PRODUCT)
源表：	DMMKT层三张产品表：
	投资理财类产品信息表(PDInvFs)
	资产类产品信息表(PDAsset)
	负债类产品信息表(PDLiabi)
开发人:	郭盼盼
开日期:	20150731
特殊说明:
变更记录:
*/
TRUNCATE TABLE MMAPST.ST_PRODUCT;
INSERT INTO MMAPST.ST_PRODUCT
(
	ETL_DATE	--跑批日期
	,TX_DATE  
	,PERIOD_ID
	,PROD_CODE	--产品代码
	,PROD_DESC	--产品描述
	,PROD_TYP_CODE	--产品类型代码
	,GLGrp_ID	--总账组号
	,RefYield_Rate	--参考收益率
	,CustYield_Rate	--客户收益率
	,YieldMod_ID	--收益模式
	,Term_No	--产品期限
	,TermUnit_ID	--期限单位
	,MinHld_Amt	--最少持有金额(人民币)
	,R_Nav		--产品净值
	,IncmBeg_Dt	--计息开始日期
	,IncmEnd_Dt	--计息结束日期
	,SourceGrp	--数据源组
)
SELECT	DISTINCT
	TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDD')) AS ETL_DATE
	,B.TX_DT
	,TO_NUMBER(TO_CHAR(B.TX_DT,'YYYYMMDD')) AS PERIOD_ID
	,UPPER(TRIM(PRODTYP_ID)) AS PROD_CODE
	,REPLACE(REPLACE(TRIM(PRODTYP_NM),'“',''),'”','') AS PROD_DESC
	,TRIM(PRODCAT_ID) AS PROD_TYP_CODE
	,NULL	 AS GLGRP_ID
	,REFYIELD_RATE
	,CUSTYIELD_RATE
	,TRIM(YIELDMOD_ID) AS YIELDMOD_ID
	,TRIM(TERM_NO) AS TERM_NO
	,TRIM(TERMUNIT_ID) AS TERMUNIT_ID
	,MINHLD_AMT
	,R_NAV
	,INCMBEG_DT
	,INCMEND_DT
	,'PDINVFS' AS	SOURCEGRP
FROM MMAPST.DMMKT_PDINVFS A
LEFT JOIN MMAPST.DMMKT_V_ZSYSTEM B
ON 1=1
WHERE TRIM(PRODTYP_NM)<>'(NULL)'
UNION ALL
SELECT	DISTINCT
	TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDD'))
	,B.TX_DT
	,TO_NUMBER(TO_CHAR(B.TX_DT,'YYYYMMDD')) AS PERIOD_ID
	,UPPER(TRIM(PRODTYP_ID))
	,REPLACE(REPLACE(TRIM(PRODTYP_NM),'“',''),'”','')
	,TRIM(PRODCAT_ID)
	,TRIM(GLGRP_ID)
	,NULL
	,NULL
	,NULL
	,NULL
	,NULL
	,NULL
	,NULL
	,NULL
	,NULL
	,'PDASSET'
FROM MMAPST.DMMKT_PDASSET A
LEFT JOIN MMAPST.DMMKT_V_ZSYSTEM B
ON 1=1
WHERE TRIM(PRODTYP_NM)<>'(NULL)'
UNION ALL
SELECT	DISTINCT
	TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDD'))
	,B.TX_DT
	,TO_NUMBER(TO_CHAR(B.TX_DT,'YYYYMMDD')) AS PERIOD_ID
	,UPPER(TRIM(PRODTYP_ID))
	,REPLACE(REPLACE(TRIM(PRODTYP_NM),'“',''),'”','')
	,TRIM(PRODCAT_ID)
	,TRIM(GLGRP_ID)
	,NULL
	,NULL
	,NULL
	,NULL
	,NULL
	,NULL
	,NULL
	,NULL
	,NULL
	,'PDLIABI'
FROM MMAPST.DMMKT_PDLIABI A
LEFT JOIN MMAPST.DMMKT_V_ZSYSTEM B
ON 1=1
WHERE TRIM(PRODTYP_NM)<>'(NULL)'
