DROP TABLE MMAPDM.DM_BRANCH;
CREATE TABLE MMAPDM.DM_BRANCH
(
 ETL_DATE NUMBER(8)        
,REGION_ID VARCHAR2(50)    
,REGION_NM VARCHAR2(50)    
,FBRNH_ID VARCHAR2(50)     
,FBRNH_NM VARCHAR2(50)     
,BRNH_ID VARCHAR2(50)      
,BRNH_NM VARCHAR2(50)      
,EQUIPMENT_ID VARCHAR2(50) 
,CHANNEL VARCHAR2(50)      
,TELEPHONE VARCHAR2(50)    
,ADDR VARCHAR2(200)        
,SOURCEGRP VARCHAR2(50)    
 );
INSERT INTO MMAPDM.DM_BRANCH
(
 ETL_DATE    
,REGION_ID   
,REGION_NM   
,FBRNH_ID    
,FBRNH_NM    
,BRNH_ID     
,BRNH_NM     
,EQUIPMENT_ID
,CHANNEL     
,TELEPHONE   
,ADDR        
,SOURCEGRP   
)
SELECT
 ETL_DATE    
,REGION_ID   
,REGION_NM   
,FBRNH_ID    
,FBRNH_NM    
,BRNH_ID     
,BRNH_NM     
,EQUIPMENT_ID
,CHANNEL     
,TELEPHONE   
,ADDR        
,SOURCEGRP   
FROM MMAPST.ST_BRANCH

