CREATE OR REPLACE PROCEDURE "MMAPDM"."P_DM_LOAN_TRANS_FLOW_HIS"
(VO_SQLERR OUT VARCHAR2)
AS
    TABLE_NAME VARCHAR2(125) :='DM_LOAN_TRANS_FLOW_HIS'; -- 表名
    DM_SQL VARCHAR2(20000);                             -- 存放SQL语句
    IO_ROW INTEGER;
    IO_STATUS INTEGER;
    V_START_TIMESTAMP TIMESTAMP;                        -- 加载开始时间
    V_END_TIMESTAMP   TIMESTAMP;                        -- 加载结束时间
    DM_TODAY NUMBER;                                    -- 数据日期"当日"
    TX_DATE NUMBER;                                     -- 数据日期
      
BEGIN
    /*针对同一天重复执行此存储过程的异常情况，插入前先删除"当日"数据*/
    SELECT TO_NUMBER(TO_CHAR((SYSDATE-1),'YYYYMMDD')) INTO DM_TODAY FROM dual;
    /*删除开始日期为"当日"的数据*/
    DELETE FROM DM_LOAN_TRANS_FLOW_HIS WHERE TO_NUMBER(TO_CHAR(TX_DATE,'YYYYMMDD')) = DM_TODAY;
    COMMIT;
      
    /*插入当日交易数据*/
    DM_SQL := 'INSERT INTO DM_LOAN_TRANS_FLOW_HIS
    (
        ETL_DATE,
		TX_DATE,
		PERIOD_ID,
		TRANS_DT,
		TRANS_TM,
		SER_NO,
		OPER_ORG,
		CUSTOMER_ID,
		ACCOUNT_ID,
		TRANSCDE_ID,
		TREATMENTCODE,
		TRANSST_ID,
		TRANSBR_ID,
		CHN_ID,
		PRODCDE_ID,
		BUSSTYP_ID,
		TRANSCURR_ID,
		TRANS_AMT,
		FEECURR_ID,
		TRANS_FEE,
		OACCTCURR_ID,
		REMARK,
		PURPDESC,
		PUTOUT_DT,
		EXPIRE_DT,
		BASE_INT,
		DEFAULT_INT,
		PAYMTHD_ID,
		VOUCHTYPE_ID,
		DEPOSITCURR_ID,
		R_DEPOSITCURR,
		EXPOSURE_AMT,
		PAYHOLD_ID,
		GUARTYPE_ID,
		RESEACCT_ORG,
		LOANACCT_ORG,
		CLIENTACCT_ORG,
		DEPOSITACCT_ORG,
		FEEACC_ORG,
		REVBRANCH_ID,
		REVBRANCH_NM,
		DEALSTART_TM,
		DEALEND_TM,
		DEAL_FG,
		REGBRANCH_ID,
		REVCIF_NM,
		LOANTYPE_ID,
		PROMISSORY_NO,
		MNCONTRACT_NO,
		CRAGREE_NO,
		CONTRACT_AMT,
		GUARN_NO,
		BILL_AMT,
		SUBJECT_NO,
		SUBJECT2_NO,
		SOURCEGRP
    )
    SELECT
        ETL_DATE,
		TX_DATE,
		PERIOD_ID,
		TRANS_DT,
		TRANS_TM,
		SER_NO,
		OPER_ORG,
		CUSTOMER_ID,
		ACCOUNT_ID,
		TRANSCDE_ID,
		TREATMENTCODE,
		TRANSST_ID,
		TRANSBR_ID,
		CHN_ID,
		PRODCDE_ID,
		BUSSTYP_ID,
		TRANSCURR_ID,
		TRANS_AMT,
		FEECURR_ID,
		TRANS_FEE,
		OACCTCURR_ID,
		REMARK,
		PURPDESC,
		PUTOUT_DT,
		EXPIRE_DT,
		BASE_INT,
		DEFAULT_INT,
		PAYMTHD_ID,
		VOUCHTYPE_ID,
		DEPOSITCURR_ID,
		R_DEPOSITCURR,
		EXPOSURE_AMT,
		PAYHOLD_ID,
		GUARTYPE_ID,
		RESEACCT_ORG,
		LOANACCT_ORG,
		CLIENTACCT_ORG,
		DEPOSITACCT_ORG,
		FEEACC_ORG,
		REVBRANCH_ID,
		REVBRANCH_NM,
		DEALSTART_TM,
		DEALEND_TM,
		DEAL_FG,
		REGBRANCH_ID,
		REVCIF_NM,
		LOANTYPE_ID,
		PROMISSORY_NO,
		MNCONTRACT_NO,
		CRAGREE_NO,
		CONTRACT_AMT,
		GUARN_NO,
		BILL_AMT,
		SUBJECT_NO,
		SUBJECT2_NO,
		SOURCEGRP
    FROM MMAPST.ST_LOAN_TRANS_FLOW';
        EXECUTE IMMEDIATE DM_SQL;
    COMMIT;
      
    /*写入日志信息*/
    IO_ROW := SQL%ROWCOUNT ;
    SELECT SYSDATE INTO V_START_TIMESTAMP FROM dual;    -- 加载程序运行开始时间
    SELECT SYSDATE INTO V_END_TIMESTAMP   FROM dual;    -- 加载程序运行结束时间
      
    IO_STATUS := 0 ;
    VO_SQLERR := 'SUSSCESS';
    P_MMAPDM_WRITE_LOGS(TABLE_NAME,IO_STATUS,IO_ROW,V_START_TIMESTAMP,V_END_TIMESTAMP,VO_SQLERR);
    COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
    ROLLBACK ;
    IO_STATUS := 9 ;
    VO_SQLERR := SQLCODE || SQLERRM ;
    SELECT SYSDATE INTO V_END_TIMESTAMP FROM dual;
    P_MMAPDM_WRITE_LOGS(TABLE_NAME,IO_STATUS,IO_ROW,V_START_TIMESTAMP,V_END_TIMESTAMP,VO_SQLERR);
END;