CREATE OR REPLACE PROCEDURE "MMAPDM"."P_DM_ACCOUNT"
(IO_STATUS OUT INTEGER,IO_SQLERR OUT VARCHAR2)
AS

  TABLE_NAME VARCHAR2(125) :='ACCOUNT';  -- 表名(修改)
BEGIN
 /*
 --编辑取数SQL
DELETE MMAPDM.MMAPDM_PROC_SQL WHERE TABLE_NAME='DM_ACCOUNT';
COMMIT;
 DECLARE
  DMSQL CLOB := '

     SELECT
TO_NUMBER(TO_CHAR(SYSDATE,''YYYYMMDD''))
,A.TX_DATE
,A.PERIOD_ID
,A.CUSTOMER_ID
,A.ACCOUNT_ID
,A.OPEN_DATE
,A.END_DATE
,A.OPEN_BRANCH
,A.ACCT_STATUS
,A.ACCT_TYPE
,C.ITEM_ID
,C.ITEM_NM
,B.PROD_CODE
,B.ACC_BAL1
,B.AVACC_MBAL1
,B.AVACC_YBAL1
,B.N_DCRTRANS
,B.N_DDRTRANS
,B.TRANS_DCRAMT1
,B.TRANS_DDRAMT1
,B.N_MCRTRANS
,B.N_MDRTRANS
,B.TRANS_MCRAMT1
,B.TRANS_MDRAMT1
,B.N_YCRTRANS
,B.N_YDRTRANS
,B.TRANS_YCRAMT1
,B.TRANS_YDRAMT1
,B.N_AVMCRTRANS
,B.N_AVMDRTRANS
,B.AVTRANS_MCRAMT1
,B.AVTRANS_MDRAMT1
,B.N_AVYCRTRANS
,B.N_AVYDRTRANS
,B.AVTRANS_YCRAMT1
,B.AVTRANS_YDRAMT1
FROM MMAPST.ST_ACCOUNT A
LEFT JOIN MMAPST.ST_ACCOUNT_AMT B
ON A.TX_DATE=B.TX_DATE
AND A.CUSTOMER_ID=B.CUSTOMER_ID
AND A.ACCOUNT_ID= B.ACCOUNT_ID
LEFT JOIN (SELECT * FROM MMAPDM.MID_ITEM A WHERE A.SOURCE_ITEM_TYP=''TOPPROD_TYPE'') C
ON B.TOPPROD_CODE=C.SOURCE_ITEM_ID
WHERE C.ITEM_ID IS NOT NULL';
BEGIN

INSERT INTO MMAPDM.MMAPDM_PROC_SQL(TABLE_NAME,DMSQL,PROC_NAME) VALUES('DM_ACCOUNT',DMSQL,'P_DM_ACCOUNT');

END;
--需要在此处添加 /
COMMIT;
*/


    P_DM_FULL(TABLE_NAME,500000,IO_STATUS,IO_SQLERR);

END P_DM_ACCOUNT;
