CREATE OR REPLACE PROCEDURE "MMAPDM"."P_DM_CUST_TRANS_STAT"
(IO_STATUS OUT INTEGER,IO_SQLERR OUT VARCHAR2)

AS

  PROCEDURE_NAME VARCHAR2(125) :='P_DM_CUST_TRANS_STAT';  -- 大存储过程名

  DM_SQL VARCHAR2(20000); -- the variable to loading the SQL statment
  IO_ROW_ALL INTEGER;
  IO_ROW INTEGER;
  ST_ROW INTEGER;  --源数据条数
  DM_ROW1 INTEGER;  --源数据条数
  DM_ROW2 INTEGER;  --源数据条数
  IO_STATUS_PREQ INTEGER;  --频度存储过程执行状态

  V_ETL_DATE NUMBER;  -- 跑批日期
  V_START_TIMESTAMP TIMESTAMP;    --the start time of procedures
  V_END_TIMESTAMP   TIMESTAMP;    --the end time of procedures

  DM_TODAY NUMBER;
  DM_YESTERDAY NUMBER;  -- 数据日期"上一日"        --
  TX_DATE NUMBER;


BEGIN

  SELECT SYSDATE INTO V_START_TIMESTAMP FROM DUAL;    -- 加载程序运行开始时间

  SELECT TO_NUMBER(TO_CHAR((SYSDATE),'YYYYMMDD')) INTO V_ETL_DATE FROM dual;  -- 取系统日期作为跑批日期

  SELECT TX_DATE INTO DM_TODAY FROM MMAPST.ST_SYSTEM_DATE;  -- 取数据日期
  SELECT PRE_DATE INTO DM_YESTERDAY FROM MMAPST.ST_SYSTEM_DATE;  -- 取数据日期"上一日"

  --查询DM层表中是否有'当日'数据
  SELECT COUNT(1) INTO DM_ROW1 FROM MMAPDM.DM_DEP_TRANS_FLOW_HIS WHERE PERIOD_ID=DM_TODAY;
  SELECT COUNT(1) INTO DM_ROW2 FROM MMAPDM.DM_LOAN_TRANS_FLOW_HIS WHERE PERIOD_ID=DM_TODAY;
--如果DM层有"当日"数据，则进行数据抽取，否则保持DM层现有数据不变。

  IF DM_ROW1>0 OR DM_ROW2 >0
  THEN

      -----------------------创建临时表-----------------------
    SELECT COUNT(1) INTO ST_ROW FROM USER_TABLES WHERE TABLE_NAME = 'TMP_CUST_TRANS_STAT';
    IF ST_ROW >0
    THEN
      DM_SQL := 'DROP TABLE MMAPDM.TMP_CUST_TRANS_STAT PURGE';
      EXECUTE  IMMEDIATE DM_SQL;
    END IF;

    DM_SQL:='CREATE TABLE MMAPDM.TMP_CUST_TRANS_STAT AS
    SELECT
      A.TX_DATE,
      A.PERIOD_ID,
      A.CUSTOMER_ID,
      A.TRANSTYP_ID,
      A.CHN_ID,
      A.TRANSBR_ID,
      A.PRODTYP_ID,
      A.TRANSDIR_FG,
      C.YEAR,
      C.QUARTER,
      C.MONTH,
      C.WEEKOFYEAR,
      C.DAYOFYEAR,
      C.DAYOFQUARTER,
      C.DAYOFMONTH,
      C.DAYOFWEEK,
      A.CUST_TRANS_AMT_LC,
      A.CUST_TRANS_CNT_LC,
      0 as CUST_TRANS_AMT_FC,
      0 as CUST_TRANS_CNT_FC,
      A.CUST_TRANS_AMT_LC as CUST_TRANS_AMT,
      A.CUST_TRANS_CNT_LC as CUST_TRANS_CNT

      FROM
      (
        SELECT
          A.TX_DATE,
          A.PERIOD_ID,
          CUSTOMER_ID,
          A.TRANSCDE_ID AS TRANSTYP_ID,
          CHN_ID,
          TRANSBR_ID,
          PRODTYP_ID,
          SUM(TRANS_AMT) AS CUST_TRANS_AMT_LC,
          COUNT(1) AS CUST_TRANS_CNT_LC,
          TRANSDIR_FG
        FROM  (
                SELECT
                  TX_DATE
                  ,PERIOD_ID
                  ,CUSTOMER_ID
                  ,TRANSCDE_ID
                  ,NVL(CHN_ID,''*'') AS CHN_ID
                  ,TRANSBR_ID
                  ,PRODTYP_ID
                  ,TRANS_AMT
                  ,TRANSDIR_FG
                FROM MMAPDM.DM_DEP_TRANS_FLOW_HIS
                UNION ALL
                SELECT
                  TX_DATE
                  ,PERIOD_ID
                  ,CUSTOMER_ID
                  ,TRANSCDE_ID
                  ,NVL(CHN_ID,''*'') AS CHN_ID
                  ,TRANSBR_ID
                  ,PRODTYP_ID
                  ,TRANS_AMT
                  ,NULL AS TRANSDIR_FG
                FROM MMAPDM.DM_LOAN_TRANS_FLOW_HIS
               ) A

        GROUP BY A.TX_DATE,A.PERIOD_ID,A.CUSTOMER_ID,A.TRANSCDE_ID,A.CHN_ID,A.TRANSBR_ID,A.PRODTYP_ID,A.TRANSDIR_FG
      ) A
      LEFT JOIN MMAPDM.MID_CALENDAR C
      ON  A.PERIOD_ID=C.PERIOD_ID
      ';
  EXECUTE  IMMEDIATE DM_SQL;
  COMMIT;

      --调度周频度数据
    P_DM_CUST_TRANS_STAT_FREQ('DM_CUST_TRANS_W_STAT','W','WEEKOFYEAR','DAYOFWEEK',7,DM_TODAY,DM_YESTERDAY,IO_ROW,IO_STATUS_PREQ,IO_SQLERR);
    IO_ROW_ALL := IO_ROW;
    IO_STATUS:=IO_STATUS_PREQ;
   --调度月频度数据
    P_DM_CUST_TRANS_STAT_FREQ('DM_CUST_TRANS_M_STAT','M','MONTH','DAYOFMONTH',6,DM_TODAY,DM_YESTERDAY,IO_ROW,IO_STATUS_PREQ,IO_SQLERR);
    IO_ROW_ALL := IO_ROW_ALL+IO_ROW;
    IO_STATUS:=IO_STATUS+IO_STATUS_PREQ;
    --调度季频度数据
    P_DM_CUST_TRANS_STAT_FREQ('DM_CUST_TRANS_Q_STAT','Q','QUARTER','DAYOFQUARTER',3,DM_TODAY,DM_YESTERDAY,IO_ROW,IO_STATUS_PREQ,IO_SQLERR);
    IO_ROW_ALL := IO_ROW_ALL+IO_ROW;
    IO_STATUS:=IO_STATUS+IO_STATUS_PREQ;
    --调度年频度数据
    P_DM_CUST_TRANS_STAT_FREQ('DM_CUST_TRANS_Y_STAT','Y','YEAR','DAYOFYEAR',2,DM_TODAY,DM_YESTERDAY,IO_ROW,IO_STATUS_PREQ,IO_SQLERR);
    IO_ROW_ALL := IO_ROW_ALL+IO_ROW;
    IO_STATUS:=IO_STATUS+IO_STATUS_PREQ;
    
/*
    写入日志
*/
    IF IO_STATUS=0
      THEN IO_SQLERR := 'SUSSCESS';
    ELSE IO_STATUS := 9 ;
         IO_SQLERR := 'P_DM_CUST_TRANS_STAT_FREQ ERROR:'||IO_SQLERR;
    END IF;
   
    ELSE   IO_STATUS:=0;
           IO_SQLERR := 'NOT EXECUTE';
    END IF;
    
    SELECT SYSDATE INTO V_END_TIMESTAMP   FROM dual;    -- 加载程序运行结束时间
    P_MMAPDM_WRITE_LOGS(PROCEDURE_NAME,IO_STATUS,IO_ROW_ALL,V_START_TIMESTAMP,V_END_TIMESTAMP,IO_SQLERR);
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
  ROLLBACK ;
  IO_STATUS := 9 ;
  IO_SQLERR := SQLCODE ||  SQLERRM  ;
  SELECT SYSDATE INTO  V_END_TIMESTAMP  FROM dual;
  P_MMAPDM_WRITE_LOGS(PROCEDURE_NAME,IO_STATUS,IO_ROW_ALL,V_START_TIMESTAMP,V_END_TIMESTAMP,IO_SQLERR);
END P_DM_CUST_TRANS_STAT;
