CREATE OR REPLACE PROCEDURE P_DM_FULL_ROLLBACK
(
	TABLE_NAME IN VARCHAR2, -- 表名
	IO_ROW OUT INTEGER  --插入条数
)
AS
	DM_SQL VARCHAR2(20000); -- 存放SQL语句
BEGIN
	IO_ROW := 0;
  -- 删除目标表中数据
  DM_SQL :='TRUNCATE TABLE MMAPDM.'||TABLE_NAME;   
  EXECUTE IMMEDIATE DM_SQL;
  COMMIT;
  --恢复备份中数据
  DM_SQL :='INSERT INTO MMAPDM.'||TABLE_NAME||' SELECT * FROM MMAPDM.'||TABLE_NAME||'_PRE';
  EXECUTE IMMEDIATE DM_SQL;
  IO_ROW := SQL%ROWCOUNT ;
  COMMIT;

END P_DM_FULL_ROLLBACK;
/
