CREATE OR REPLACE PROCEDURE P_DM_CUST_TRANS_STAT_ROLLBACK (
    TABLE_NAME IN VARCHAR2, --表名
    DM_TODAY IN NUMBER,--当日
    DM_YESTERDAY IN NUMBER, -- 数据日期"上一日"
    FREQ IN VARCHAR2 --频度
   )
   AS
       DM_SQL VARCHAR2(20000);
   BEGIN
     DM_SQL :='UPDATE MMAPDM.'||TABLE_NAME||' SET FREQ_DIFF = FREQ_DIFF - 1
        WHERE (SELECT DAYOFWEEK FROM MMAPST.MID_CALENDAR WHERE PERIOD_ID='||DM_TODAY||')=1
      ';
    EXECUTE IMMEDIATE DM_SQL;
    COMMIT;
    DM_SQL:= 'INSERT INTO MMAPDM.'||TABLE_NAME||'
        (ETL_DATE
        ,TX_DATE
        ,PERIOD_ID
        ,FREQ
        ,YEAR
        ,FREQ_VALUE
        ,FREQ_DIFF
        ,CUSTOMER_ID
        ,TransTyp_ID
        ,CHANNEL
        ,TransBr_ID
        ,PROD_TYPE
        ,CUST_TRANS_AMT_LC
        ,CUST_TRANS_AMT_CWS_LC
        ,CUST_TRANS_AMT_SQT_LC
        ,CUST_TRANS_AMT_MAX_LC
        ,CUST_TRANS_AMT_MAX_DATE_LC
        ,CUST_TRANS_AMT_MIN_LC
        ,CUST_TRANS_AMT_MIN_DATE_LC
        ,CUST_TRANS_AMT_AVG_LC
        ,CUST_TRANS_AMT_AVG_CWS_LC
        ,CUST_TRANS_AMT_AVG_SQT_LC
        ,CUST_TRANS_CNT_LC
        ,CUST_TRANS_CNT_CWS_LC
        ,CUST_TRANS_CNT_SQT_LC
        ,CUST_TRANS_CNT_MAX_LC
        ,CUST_TRANS_CNT_MAX_DATE_LC
        ,CUST_TRANS_CNT_MIN_LC
        ,CUST_TRANS_CNT_MIN_DATE_LC
        ,CUST_TRANS_CNT_AVG_LC
        ,CUST_TRANS_CNT_AVG_CWS_LC
        ,CUST_TRANS_CNT_AVG_SQT_LC
        ,CUST_TRANS_AMT_FC
        ,CUST_TRANS_AMT_CWS_FC
        ,CUST_TRANS_AMT_SQT_FC
        ,CUST_TRANS_AMT_MAX_FC
        ,CUST_TRANS_AMT_MAX_DATE_FC
        ,CUST_TRANS_AMT_MIN_FC
        ,CUST_TRANS_AMT_MIN_DATE_FC
        ,CUST_TRANS_AMT_AVG_FC
        ,CUST_TRANS_AMT_AVG_CWS_FC
        ,CUST_TRANS_AMT_AVG_SQT_FC
        ,CUST_TRANS_CNT_FC
        ,CUST_TRANS_CNT_CWS_FC
        ,CUST_TRANS_CNT_SQT_FC
        ,CUST_TRANS_CNT_MAX_FC
        ,CUST_TRANS_CNT_MAX_DATE_FC
        ,CUST_TRANS_CNT_MIN_FC
        ,CUST_TRANS_CNT_MIN_DATE_FC
        ,CUST_TRANS_CNT_AVG_FC
        ,CUST_TRANS_CNT_AVG_CWS_FC
        ,CUST_TRANS_CNT_AVG_SQT_FC
        ,CUST_TRANS_AMT
        ,CUST_TRANS_AMT_CWS
        ,CUST_TRANS_AMT_SQT
        ,CUST_TRANS_AMT_MAX
        ,CUST_TRANS_AMT_MAX_DATE
        ,CUST_TRANS_AMT_MIN
        ,CUST_TRANS_AMT_MIN_DATE
        ,CUST_TRANS_AMT_AVG
        ,CUST_TRANS_AMT_AVG_CWS
        ,CUST_TRANS_AMT_AVG_SQT
        ,CUST_TRANS_CNT
        ,CUST_TRANS_CNT_CWS
        ,CUST_TRANS_CNT_SQT
        ,CUST_TRANS_CNT_MAX
        ,CUST_TRANS_CNT_MAX_DATE
        ,CUST_TRANS_CNT_MIN
        ,CUST_TRANS_CNT_MIN_DATE
        ,CUST_TRANS_CNT_AVG
        ,CUST_TRANS_CNT_AVG_CWS
        ,CUST_TRANS_CNT_AVG_SQT
        ,NEW_FLAG
        )

    SELECT

        ETL_DATE
        ,TX_DATE
        ,PERIOD_ID
        ,FREQ
        ,YEAR
        ,FREQ_VALUE
        ,FREQ_DIFF
        ,CUSTOMER_ID
        ,TransTyp_ID
        ,CHANNEL
        ,TransBr_ID
        ,PROD_TYPE
        ,CUST_TRANS_AMT_LC
        ,CUST_TRANS_AMT_CWS_LC
        ,CUST_TRANS_AMT_SQT_LC
        ,CUST_TRANS_AMT_MAX_LC
        ,CUST_TRANS_AMT_MAX_DATE_LC
        ,CUST_TRANS_AMT_MIN_LC
        ,CUST_TRANS_AMT_MIN_DATE_LC
        ,CUST_TRANS_AMT_AVG_LC
        ,CUST_TRANS_AMT_AVG_CWS_LC
        ,CUST_TRANS_AMT_AVG_SQT_LC
        ,CUST_TRANS_CNT_LC
        ,CUST_TRANS_CNT_CWS_LC
        ,CUST_TRANS_CNT_SQT_LC
        ,CUST_TRANS_CNT_MAX_LC
        ,CUST_TRANS_CNT_MAX_DATE_LC
        ,CUST_TRANS_CNT_MIN_LC
        ,CUST_TRANS_CNT_MIN_DATE_LC
        ,CUST_TRANS_CNT_AVG_LC
        ,CUST_TRANS_CNT_AVG_CWS_LC
        ,CUST_TRANS_CNT_AVG_SQT_LC
        ,CUST_TRANS_AMT_FC
        ,CUST_TRANS_AMT_CWS_FC
        ,CUST_TRANS_AMT_SQT_FC
        ,CUST_TRANS_AMT_MAX_FC
        ,CUST_TRANS_AMT_MAX_DATE_FC
        ,CUST_TRANS_AMT_MIN_FC
        ,CUST_TRANS_AMT_MIN_DATE_FC
        ,CUST_TRANS_AMT_AVG_FC
        ,CUST_TRANS_AMT_AVG_CWS_FC
        ,CUST_TRANS_AMT_AVG_SQT_FC
        ,CUST_TRANS_CNT_FC
        ,CUST_TRANS_CNT_CWS_FC
        ,CUST_TRANS_CNT_SQT_FC
        ,CUST_TRANS_CNT_MAX_FC
        ,CUST_TRANS_CNT_MAX_DATE_FC
        ,CUST_TRANS_CNT_MIN_FC
        ,CUST_TRANS_CNT_MIN_DATE_FC
        ,CUST_TRANS_CNT_AVG_FC
        ,CUST_TRANS_CNT_AVG_CWS_FC
        ,CUST_TRANS_CNT_AVG_SQT_FC
        ,CUST_TRANS_AMT
        ,CUST_TRANS_AMT_CWS
        ,CUST_TRANS_AMT_SQT
        ,CUST_TRANS_AMT_MAX
        ,CUST_TRANS_AMT_MAX_DATE
        ,CUST_TRANS_AMT_MIN
        ,CUST_TRANS_AMT_MIN_DATE
        ,CUST_TRANS_AMT_AVG
        ,CUST_TRANS_AMT_AVG_CWS
        ,CUST_TRANS_AMT_AVG_SQT
        ,CUST_TRANS_CNT
        ,CUST_TRANS_CNT_CWS
        ,CUST_TRANS_CNT_SQT
        ,CUST_TRANS_CNT_MAX
        ,CUST_TRANS_CNT_MAX_DATE
        ,CUST_TRANS_CNT_MIN
        ,CUST_TRANS_CNT_MIN_DATE
        ,CUST_TRANS_CNT_AVG
        ,CUST_TRANS_CNT_AVG_CWS
        ,CUST_TRANS_CNT_AVG_SQT
        ,NEW_FLAG
        

    FROM  MMAPDM.DM_CUST_TRANS_STAT_PRE
    WHERE FREQ='''||FREQ||'''
    AND PERIOD_ID='||DM_YESTERDAY
    ;
    EXECUTE  IMMEDIATE DM_SQL;
    COMMIT;

   END P_DM_CUST_TRANS_STAT_ROLLBACK;
