CREATE OR REPLACE PROCEDURE P_DM_ACCOUNT_INVEST
(IO_STATUS OUT INTEGER,IO_SQLERR OUT VARCHAR2)
AS
	TABLE_NAME VARCHAR2(125) :='ACCOUNT_INVEST';  -- 客户投资类账户表
BEGIN
/*
INSERT INTO MMAPDM.MMAPDM_PROC_SQL(TABLE_NAME,DMSQL,PROC_NAME) VALUES('DM_ACCOUNT_INVEST','
      select
  to_number(to_char((SYSDATE),''YYYYMMDD'')),
  a.TX_DATE,
  a.PERIOD_ID,
  a.CUSTOMER_ID,
  a.ACCOUNT_ID,
  a.ThirdPart_ACCOUNT_ID,
  a.ACCT_TYPE,
  a.ACCT_STATUS,
  a.OPEN_BRANCH,
  a.OPEN_DATE,
  a.END_DATE,
  b.PROD_TYPE_CODE,
  a.PROD_CODE,
  a.ACCT_BAL
from MMAPST.ST_ACCOUNT_INVEST a left join MMAPDM.DM_PRODUCT b on a.PROD_CODE = b.PROD_CODE','P_DM_ACCOUNT_INVEST')
;
*/
    P_DM_FULL(TABLE_NAME,10000,IO_STATUS,IO_SQLERR);
END P_DM_ACCOUNT_INVEST;
/
