CREATE OR REPLACE PROCEDURE "MMAPDM"."P_DM_PRODUCT"
(IO_STATUS OUT INTEGER,IO_SQLERR OUT VARCHAR2)
AS

  TABLE_NAME VARCHAR2(125) :='PRODUCT';  -- 表名(修改)
BEGIN
 /*
 --编辑取数SQL
DELETE MMAPDM.MMAPDM_PROC_SQL WHERE TABLE_NAME='DM_PRODUCT';
COMMIT;
 DECLARE
  DMSQL CLOB := '

      SELECT
        TO_NUMBER(TO_CHAR((SYSDATE),''YYYYMMDD'')) AS ETL_DATE
        ,A.TX_DATE
        ,A.PERIOD_ID
        ,A.PROD_CODE
        ,A.PROD_DESC
        ,NULL  AS PROD_START_DT
        ,NULL  AS PROD_END_DT
        ,''LOAN'' AS PROD_TYPE_CODE
        ,''贷款'' AS PROD_TYPE_DESC
        ,NULL  AS PROD_MID_CODE
        ,NULL  AS PROD_MID_DESC
        ,NULL  AS PROD_DET1_CODE
        ,NULL  AS PROD_DET1_DESC
        ,NULL  AS PROD_DET2_CODE
        ,NULL  AS PROD_DET2_DESC
        ,NULL  AS PROD_IND_CODE
        ,NULL  AS PROD_IND_DESC
      FROM MMAPST.ST_PRODUCT A
      WHERE SOURCEGRP=''PDASSET''
      UNION ALL
      SELECT
        TO_NUMBER(TO_CHAR((SYSDATE),''YYYYMMDD'')) AS ETL_DATE
        ,A.TX_DATE
        ,A.PERIOD_ID
        ,A.PROD_CODE
        ,A.PROD_DESC
        ,INCMBEG_DT AS PROD_START_DT
        ,INCMEND_DT AS PROD_END_DT
        ,''FIN'' AS PROD_TYPE_CODE
        ,''理财'' AS PROD_TYPE_DESC
        ,SUBSTR(PROD_CODE,1,2) AS PROD_MID_CODE
        ,SUBSTR(PROD_DESC,1,2) AS PROD_MID_DESC
        ,Term_No AS PROD_DET1_CODE
        ,NULL  AS PROD_DET1_DESC
        ,TermUnit_ID AS PROD_DET2_CODE
        ,CASE  TermUnit_ID
          WHEN ''D'' THEN  ''天''
          WHEN ''M'' THEN  ''月''
          WHEN ''Y'' THEN  ''年''
         END AS PROD_DET2_DESC
        ,NULL  AS PROD_IND_CODE
        ,NULL  AS PROD_IND_DESC
      FROM MMAPST.ST_PRODUCT A
      WHERE SOURCEGRP=''PDINVFS''
      AND PROD_TYP_CODE=''1''
      AND LENGTH(PROD_CODE)=7
      UNION ALL
      SELECT
        TO_NUMBER(TO_CHAR((SYSDATE),''YYYYMMDD'')) AS ETL_DATE
        ,A.TX_DATE
        ,A.PERIOD_ID
        ,A.PROD_CODE
        ,A.PROD_DESC
        ,INCMBEG_DT AS PROD_START_DT
        ,INCMEND_DT AS PROD_END_DT
        ,''FOUND'' AS  PROD_TYPE_CODE
        ,''基金'' AS PROD_TYPE_DESC
        ,NULL  AS PROD_MID_CODE
        ,NULL  AS PROD_MID_DESC
        ,Term_No AS PROD_DET1_CODE
        ,NULL  AS PROD_DET1_DESC
        ,TermUnit_ID AS PROD_DET2_CODE
        ,CASE  TermUnit_ID
          WHEN ''D'' THEN  ''天''
          WHEN ''M'' THEN  ''月''
          WHEN ''Y'' THEN  ''年''
         END AS PROD_DET2_DESC
        ,NULL  AS PROD_IND_CODE
        ,NULL  AS PROD_IND_DESC
      FROM MMAPST.ST_PRODUCT A
      WHERE SOURCEGRP=''PDINVFS''
      AND PROD_TYP_CODE=''0''
      UNION ALL
      SELECT
        TO_NUMBER(TO_CHAR((SYSDATE),''YYYYMMDD'')) AS ETL_DATE
        ,A.TX_DATE
        ,A.PERIOD_ID
        ,A.PROD_CODE
        ,A.PROD_DESC
        ,INCMBEG_DT AS PROD_START_DT
        ,INCMEND_DT AS PROD_END_DT
        ,''NDEBT'' AS  PROD_TYPE_CODE
        ,''国债'' AS PROD_TYPE_DESC
        ,''ENDEBT'' AS PROD_MID_CODE
        ,''电子式国债'' AS PROD_MID_DESC
        ,Term_No AS PROD_DET1_CODE
        ,NULL  AS PROD_DET1_DESC
        ,TermUnit_ID AS PROD_DET2_CODE
        ,CASE  TermUnit_ID
          WHEN ''D'' THEN  ''天''
          WHEN ''M'' THEN  ''月''
          WHEN ''Y'' THEN  ''年''
         END AS PROD_DET2_DESC
        ,NULL  AS PROD_IND_CODE
        ,NULL  AS PROD_IND_DESC
      FROM MMAPST.ST_PRODUCT A
      WHERE SOURCEGRP=''PDINVFS''
      AND PROD_TYP_CODE=''B''
      UNION ALL
      SELECT
        TO_NUMBER(TO_CHAR((SYSDATE),''YYYYMMDD'')) AS ETL_DATE
        ,A.TX_DATE
        ,A.PERIOD_ID
        ,A.PROD_CODE
        ,A.PROD_DESC
        ,NULL  AS PROD_START_DT
        ,NULL  AS PROD_END_DT
        ,''NDEBT'' AS  PROD_TYPE_CODE
        ,''国债'' AS PROD_TYPE_DESC
        ,''ENDEBT'' AS PROD_MID_CODE
        ,''电子式国债'' AS PROD_MID_DESC
        ,TO_NUMBER(SUBSTR(A.PROD_CODE,INSTR（A.PROD_CODE,''-'',1,1）+1,INSTR（A.PROD_CODE,''-'',1,2）-1-INSTR（A.PROD_CODE,''-'',1,1）)) AS PROD_DET1_CODE
        ,NULL  AS PROD_DET1_DESC
        ,CASE  WHEN INSTR（A.PROD_CODE,''-'',1,2）> 0 THEN SUBSTR(A.PROD_CODE,-1,1) END  AS PROD_DET2_CODE
        ,CASE  SUBSTR(A.PROD_CODE,-1,1)
          WHEN ''D'' THEN  ''天''
          WHEN ''M'' THEN  ''月''
          WHEN ''Y'' THEN  ''年''
         END AS PROD_DET2_DESC
        ,NULL  AS PROD_IND_CODE
        ,NULL  AS PROD_IND_DESC
      FROM MMAPST.ST_PRODUCT A
      WHERE SOURCEGRP=''PDLIABI''
      AND PROD_DESC LIKE ''%电子国债%''
      UNION ALL
      SELECT
        TO_NUMBER(TO_CHAR((SYSDATE),''YYYYMMDD'')) AS ETL_DATE
        ,A.TX_DATE
        ,A.PERIOD_ID
        ,A.PROD_CODE
        ,A.PROD_DESC
        ,NULL  AS PROD_START_DT
        ,NULL  AS PROD_END_DT
        ,''NDEBT'' AS  PROD_TYPE_CODE
        ,''国债'' AS PROD_TYPE_DESC
        ,''PNDEBT'' AS PROD_MID_CODE
        ,''凭证式国债'' AS PROD_MID_DESC
        ,TO_NUMBER(SUBSTR(A.PROD_CODE,INSTR（A.PROD_CODE,''-'',1,1）+1,INSTR（A.PROD_CODE,''-'',1,2）-1-INSTR（A.PROD_CODE,''-'',1,1）)) AS PROD_DET1_CODE
        ,NULL  AS PROD_DET1_DESC
        ,CASE  WHEN INSTR（A.PROD_CODE,''-'',1,2）> 0 THEN SUBSTR(A.PROD_CODE,-1,1) END  AS PROD_DET2_CODE
        ,CASE  SUBSTR(A.PROD_CODE,-1,1)
          WHEN ''D'' THEN  ''天''
          WHEN ''M'' THEN  ''月''
          WHEN ''Y'' THEN  ''年''
         END AS PROD_DET2_DESC
        ,NULL  AS PROD_IND_CODE
        ,NULL  AS PROD_IND_DESC
      FROM MMAPST.ST_PRODUCT A
      WHERE SOURCEGRP=''PDLIABI''
      AND PROD_DESC LIKE ''%凭证%''
      UNION ALL
      SELECT
        TO_NUMBER(TO_CHAR((SYSDATE),''YYYYMMDD'')) AS ETL_DATE
        ,A.TX_DATE
        ,A.PERIOD_ID
        ,A.PROD_CODE
        ,A.PROD_DESC
        ,NULL  AS PROD_START_DT
        ,NULL  AS PROD_END_DT
        ,''TD'' AS PROD_TYPE_CODE
        ,''定期存款''  AS PROD_TYPE_DESC
        ,SUBSTR(A.PROD_CODE,1,2) AS PROD_MID_CODE
        ,A.PROD_DESC AS PROD_MID_DESC
        ,TO_NUMBER(SUBSTR(A.PROD_CODE,INSTR（A.PROD_CODE,''-'',1,1）+1,INSTR（A.PROD_CODE,''-'',1,2）-1-INSTR（A.PROD_CODE,''-'',1,1）)) AS PROD_DET1_CODE
        ,NULL  AS PROD_DET1_DESC
        ,CASE  WHEN INSTR（A.PROD_CODE,''-'',1,2）> 0 THEN SUBSTR(A.PROD_CODE,-1,1) END AS PROD_DET2_CODE
        ,CASE  SUBSTR(A.PROD_CODE,-1,1)
          WHEN ''D'' THEN  ''天''
          WHEN ''M'' THEN  ''月''
          WHEN ''Y'' THEN  ''年''
         END AS PROD_DET2_DESC
        ,NULL  AS PROD_IND_CODE
        ,NULL  AS PROD_IND_DESC
      FROM MMAPST.ST_PRODUCT A
      WHERE SOURCEGRP=''PDLIABI''
      AND ( PROD_DESC  NOT  LIKE ''%理财%'' AND PROD_DESC NOT  LIKE  ''%国债%'')
      AND PROD_TYP_CODE NOT IN(''D'',''S'')
      UNION ALL
      SELECT
        TO_NUMBER(TO_CHAR((SYSDATE),''YYYYMMDD'')) AS ETL_DATE
        ,A.TX_DATE
        ,A.PERIOD_ID
        ,A.PROD_CODE
        ,A.PROD_DESC
        ,NULL  AS PROD_START_DT
        ,NULL  AS PROD_END_DT
        ,''CD'' AS PROD_TYPE_CODE
        ,''活期存款''  AS PROD_TYPE_DESC
        ,SUBSTR(A.PROD_CODE,1,2) AS PROD_MID_CODE
        ,A.PROD_DESC AS PROD_MID_DESC
        ,TO_NUMBER(SUBSTR(A.PROD_CODE,INSTR（A.PROD_CODE,''-'',1,1）+1,INSTR（A.PROD_CODE,''-'',1,2）-1-INSTR（A.PROD_CODE,''-'',1,1）)) AS PROD_DET1_CODE
        ,NULL  AS PROD_DET1_DESC
        ,CASE  WHEN INSTR（A.PROD_CODE,''-'',1,2）> 0 THEN SUBSTR(A.PROD_CODE,-1,1) END AS PROD_DET2_CODE
        ,CASE  SUBSTR(A.PROD_CODE,-1,1)
          WHEN ''D'' THEN  ''天''
          WHEN ''M'' THEN  ''月''
          WHEN ''Y'' THEN  ''年''
         END AS PROD_DET2_DESC
        ,NULL  AS PROD_IND_CODE
        ,NULL  AS PROD_IND_DESC
      FROM MMAPST.ST_PRODUCT A
      WHERE SOURCEGRP=''PDLIABI''
      AND PROD_TYP_CODE IN(''D'',''S'')';
BEGIN

INSERT INTO MMAPDM.MMAPDM_PROC_SQL(TABLE_NAME,DMSQL,PROC_NAME) VALUES('DM_PRODUCT',DMSQL,'P_DM_PRODUCT');

END;
--需要在此处添加 /
COMMIT;
*/


    P_DM_FULL(TABLE_NAME,500000,IO_STATUS,IO_SQLERR);

END P_DM_PRODUCT;
