CREATE OR REPLACE PROCEDURE P_DM_ACCOUNT_INVEST
(IO_STATUS OUT INTEGER,IO_SQLERR OUT VARCHAR2)
AS
	TABLE_NAME VARCHAR2(125) :='ACCOUNT_INVEST';  -- 客户投资类账户表
BEGIN
    P_DM_FULL(TABLE_NAME,10000,IO_STATUS,IO_SQLERR);
END P_DM_ACCOUNT_INVEST;
/
